version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2023.09.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: "Kotlinter"
          command: ./gradlew lintKotlin
      - run:
          name: "Detekt"
          command: ./gradlew detektMain
      - run:
          name: "Lint"
          command: ./gradlew lint
      - android/run-tests:
          test-command: ./gradlew check
      - run:
          name: "Assemble"
          command: ./gradlew assembleDebug
      - android/save-gradle-cache
      - android/save-build-cache
#  tests:
#    executor:
#      name: android/android-docker
#      tag: 2023.09.1
#    steps:
#      - checkout
#      - android/restore-gradle-cache
#      - android/run-tests:
#          test-command: ./gradlew check
#      - android/save-gradle-cache
#  assemble:
#    executor:
#      name: android/android-docker
#      tag: 2023.09.1
#    steps:
#      - checkout
#      - android/restore-gradle-cache
#      - android/restore-build-cache
#      - run:
#          name: "Assemble"
#          command: ./gradlew assembleDebug
#      - android/save-gradle-cache

workflows:
  linting:
    jobs:
      - build
#      - tests
#      - assemble
