version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2023.09.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache

workflows:
  test-and-build:
    jobs:
      - unit-test
