[versions]
androidGradlePlugin = "7.4.0"
compileSdk = "33"
compose = "1.3.1"
jvmTarget = "11"
minSdk = "26"
targetSdk = "33"
versionCode = "200"
versionName = "1.0.0"
room = "2.4.3"

# Raise these two together
kotlin = "1.7.10"
ksp = "1.7.10-1.0.6"
##########################

[libraries]
androidx-activityCompose = "androidx.activity:activity-compose:1.6.1"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.5.3"
androidx-coreKtx = "androidx.core:core-ktx:1.9.0"
androidx-lifecycle-runtimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
timber = "com.jakewharton.timber:timber:5.0.1"
vico-compose = "com.patrykandpatrick.vico:compose-m3:1.6.3"

# Debug libraries
debug-androidx-compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
debug-androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

# Test libraries
test-androidx-compose-uiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
test-androidx-espresso = "androidx.test.espresso:espresso-core:3.5.0"
test-androidx-junit = "androidx.test.ext:junit:1.1.4"
test-junit = "junit:junit:4.13.2"
test-kotest-property = "io.kotest:kotest-property:5.5.4"

[bundles]
androidTest = [
    "test-androidx-compose-uiTestJunit4",
    "test-androidx-espresso",
    "test-androidx-junit",
    "test-kotest-property"
]
androidx = [
    "androidx-activityCompose",
    "androidx-compose-material",
    "androidx-compose-ui",
    "androidx-compose-uiToolingPreview",
    "androidx-coreKtx",
    "androidx-lifecycle-runtimeKtx",
    "androidx-compose-navigation",
    "androidx-room-runtime",
    "androidx-room-ktx"
]
debug = [
    "debug-androidx-compose-uiTestManifest",
    "debug-androidx-compose-uiTooling",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
benManes-versions = "com.github.ben-manes.versions:0.44.0"
detekt = "io.gitlab.arturbosch.detekt:1.22.0"
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:11.0.0"
littlerobots = "nl.littlerobots.version-catalog-update:0.7.0"
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
