name: CI
on:
  pull_request:
    branches: [ main ]
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache gradle dependencies
        uses: actions/setup-java@v4
        with:
          cache: "gradle"

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektRelease

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlinRelease

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintAnalyzeRelease

      - name: Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testReleaseUnitTest

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "release.keystore"
          fileDir: "${{ github.workspace }}/app/keystore"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}
