name: CI
on:
  pull_request:
    branches: [ main ]
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: azul

      - name: Setup Android SDK
        uses: amyu/setup-android@v4

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint

      - name: Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "release.keystore"
          fileDir: "${{ github.workspace }}/app/keystore"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}
