name: Development
run-name: Development
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Clean
        run: ./gradlew clean
      - name: Build
        run: ./gradlew build
