name: Development
run-name: Development
on: pull_request
jobs:
  development:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt + KtLint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektRelease ktlintReleaseSourceSetCheck

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintAnalyzeRelease

      - name: Compile
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileReleaseSources

      - name: Connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest
