name: Development
run-name: Development
on: [ pull_request ]
jobs:
  development:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Detekt
        run: ./gradlew detekt

      - name: Ktlint
        run: ./gradlew ktlintCheck

      - name: Lint
        run: ./gradlew lintAnalyzeDebug

      - name: Assemble
        run: ./gradlew assembleDebug

      - name: Connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
