name: ktlintCheck
run-name: ktlintCheck
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: ktlintCheck
        run: ./gradlew ktlintCheck
