name: CI
on: pull_request
jobs:
  pull_request:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektRelease

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlinRelease lintKotlinAndroidTestRelease

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintRelease

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.keystore'
          fileDir: '${{ github.workspace }}/Daedalus/keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}

      - name: Connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest
