name: CI
on:
  pull_request:
    branches: main
    types: [ synchronize, opened, reopened, ready_for_review ]
jobs:
  pull_request:
    runs-on: ubuntu-latest
    if: false # Do not run anything on a draft PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektMain

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint

      - name: Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.keystore'
          fileDir: '${{ github.workspace }}/Daedalus/keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}
