name: CI
on:
  pull_request:
    branches: main
    types: [ synchronize, opened, reopened, ready_for_review ]
jobs:
  pull_request:
    runs-on: macos-latest
    if: github.event.pull_request.draft == false # Do not run anything on a draft PR
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektRelease

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlinRelease lintKotlinAndroidTestRelease

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintRelease

      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testReleaseUnitTest

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.keystore'
          fileDir: '${{ github.workspace }}/Daedalus/keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}
