name: Build Release App Bundle
on: workflow_dispatch
jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ secrets.KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > Daedalus/keystore/release.keystore

      - name: Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build release
        run: ./gradlew Daedalus:bundleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}

      - name: Report
        if: always()
        run: ./gradlew signingReport

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: Daedalus/build/outputs
