name: Build Release App Bundle
on: workflow_dispatch
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.keystore'
          fileDir: '${{ github.workspace }}/Daedalus/keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build release
        run: ./gradlew Daedalus:bundleRelease
        env:
          DAEDALUS_SIGNING_KEY: ${{ secrets.DAEDALUS_SIGNING_KEY }}
          DAEDALUS_STORE_PASSWORD: ${{ secrets.DAEDALUS_STORE_PASSWORD }}
          DAEDALUS_SIGNING_KEY_PASSWORD: ${{ secrets.DAEDALUS_SIGNING_KEY_PASSWORD }}

      - name: Upload release to Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: com.rjspies.daedalus
          releaseFiles: Daedalus/build/outputs/bundle/release/Daedalus-release.aab
          track: internal
          status: draft
          mappingFile: Daedalus/build/outputs/mapping/release/mapping.txt
          debugSymbols: Daedalus/intermediates/merged_native_libs/release/out/lib
